version: '3.8'

services:
  frontend:
    container_name: tcp2-frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend

  backend:
    container_name: tcp2-backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=tcp2_db
    depends_on:
      - db

  db:
    container_name: tcp2-db
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=tcp2_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  frontend_node_modules:
  backend_node_modules:
